Repository csubhasundar/CodingPractice-Hacktoberfest23, pull requests merged in 2023-10, with the labels that each got.

#2 Create calculator.c
  C/calculator.c
Labels: hacktoberfest-accepted2023

#30 Added Graph implementations(adjacency matrix and list) code in cpp
  C++/Graph/Adjacency_Matrix.cpp
  C++/Graph/Graph_AdjacencyList.cpp
Labels: hacktoberfest-accepted2023, hacktoberfest-accepted

#5 Create createpattern
  C/createpattern
Labels: hacktoberfest-accepted

#29 Create Dijkstra's_Algorithm.cpp
  C++/Dijkstra's_Algorithm.cpp
Labels: hacktoberfest-accepted

#8 Create Fibonacci_Series.cpp
  C++/Fibonacci_Series.cpp
Labels: hacktoberfest-accepted2023, hacktoberfest-accepted

#22 Create nim.py
  Python/nim.py
Labels: hacktoberfest-accepted

#27 Program to find the number of Keywords in a given text file !!!
  C/To_find_keywords.c
  C/To_find_keywords.txt
Labels: hacktoberfest-accepted

#24 Selection Sort using Python
  Python/Selection Sort using Python
Labels: hacktoberfest-accepted

#23 Create Bubble_Sort
  Python/Bubble_Sort
Labels: hacktoberfest-accepted

#31 Create medianTwoSortedArrays.java (Leetcode Hard)
  Java/medianTwoSortedArrays.java
Labels: hacktoberfest-accepted

#25 Insertion Sort using Python
  Python/Insertion Sort using Python
Labels: hacktoberfest-accepted

#10 SelectionSortAlgo.cpp
  SelectionSortAlgo.cpp
Labels: hacktoberfest-accepted

#28 Create BFS.cpp
  C++/BFS.cpp
Labels: hacktoberfest-accepted

#20 Added trees and LinkedList in C++
  C++/linkedlist.cpp
  C++/trees.cpp
Labels: hacktoberfest-accepted

#11 ShellSortingAlgo.java
  Java/ShellSortingAlgo.java
Labels: hacktoberfest-accepted

#13 Add : To add bubble_sort.c
  C/bubble_sort.c
Labels: hacktoberfest-accepted

#16 Add Set Operations in CPP
  C++/SetOperations.cpp
Labels: hacktoberfest-accepted

#32 Create 123Pattern.java (Leetcode Medium)
  Java/123Pattern.java
Labels: hacktoberfest-accepted2023, hacktoberfest-accepted

#19 Create Distinct_Subsequences.cpp
  C++/Distinct_Subsequences.cpp
Labels: hacktoberfest-accepted

#18 added a python project of a telephone directory
  Python/telephone_directory.py
Labels: hacktoberfest-accepted

#33 Create ReverseWordsInString-III.java (Leetcode Easy)
  Java/ReverseWordsInString-III.java
Labels: hacktoberfest-accepted

#35 Heap sort.cpp
  C++/Heap sort.cpp
Labels: hacktoberfest-accepted

#37 Add : To add atm.py
  Python/atm.py
Labels: hacktoberfest-accepted

#36 Web Scrapper in PHP
  PHP/Web-Scrapper/Php and Database Connection.php
  PHP/Web-Scrapper/README.md
  PHP/Web-Scrapper/crawl.php
  PHP/Web-Scrapper/crawler.sql
Labels: hacktoberfest-accepted

#34 Added code for hashing.cpp
  C++/Minimum number of subsets with distinct elements
Labels: hacktoberfest-accepted

#38 Update 4-Sum_Problem.cpp
  C++/4-Sum_Problem.cpp
Labels: hacktoberfest-accepted

#39 Implemented Menu Driven Program for Stack using Arrays in Java with Manual and Automated Testing using Junit.
  Java/Stack.java
  Java/StackTest.java
  Java/StackTest.txt
Labels: hacktoberfest-accepted

#40 Created TwoSum.java
  Java/TwoSum.java
Labels: hacktoberfest-accepted

#41 Rock,paper scissor.c
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  C/rps.c
  C/rps.exe
Labels: hacktoberfest-accepted

#43 Created solution for Leetcode problem 15. 3Sum in java.
  Java/3Sum.java
  Java/AddTwoNumbers.java
  Java/MergeSortedLists.java
Labels: hacktoberfest-accepted

#44 Added random number guess game in Python
  Python/guess_the_number.py
Labels: hacktoberfest-accepted

#47 stock_maxprofit program added
  C++/stock_max_profit.cpp
Labels: hacktoberfest-accepted

#48 Added Linear search in C++
  C++/binarysearch.cpp
  C++/linearsearch.cpp
Labels: hacktoberfest-accepted

#50 Update Insertion Sort using Python
  Python/Insertion Sort using Python
Labels: hacktoberfest-accepted

#53 myreq
  bubblesort.cpp
Labels: hacktoberfest-accepted

#51 Added Kadane's Algorithm under Python
  Python/kadanes_algorithm.py
Labels: hacktoberfest-accepted

#49 Fix issue #45: Added Binary Search Algorithm in C
  C/binary_search.c
Labels: hacktoberfest-accepted

#54 added some codestudio Linkedlist programs
  Java/Linkedlist_Codestudio/Addone.java
  Java/Linkedlist_Codestudio/DeleteLastNode.java
  Java/Linkedlist_Codestudio/DeleteNodeUsingOnePointer.java
  Java/Linkedlist_Codestudio/DoubleLL.java
  Java/Linkedlist_Codestudio/FindMiddle.java
  Java/Linkedlist_Codestudio/Linkedlistremovenodefromlast.java
  Java/Linkedlist_Codestudio/MaxSubarrSum.java
  Java/Linkedlist_Codestudio/Sort012.java
  Java/Linkedlist_Codestudio/SortLL.java
Labels: hacktoberfest-accepted

#55 kth smallest element
  Python/kth largest element
Labels: hacktoberfest-accepted

#58 binarysearchalgo.java
  Java/binarysearchalgo.java
Labels: hacktoberfest-accepted

#57 marksheet in javascript
  Javascript/marksheet.js
Labels: hacktoberfest-accepted

#59 binarysearchalgo.py
  Python/binarysearchalgo.py
Labels: hacktoberfest-accepted

#64 Implementation of Binary Search Algorithm
  C/BinarySearch.c
Labels: hacktoberfest-accepted

#60 created CRUD using mysql in python
  Python/crud.py
Labels: hacktoberfest-accepted

#63 Added Primality test Algorithm
  C++/ISPRIME.cpp
  C++/MillerRabin.cpp
Labels: hacktoberfest-accepted

#62 Added balanced paranthesis problem
  C++/balanced_paranthesis.cpp
Labels: hacktoberfest-accepted

#88 Create Compute.C
  C/Compute.C
Labels: hacktoberfest-accepted2023, hacktoberfest-accepted

#87 create PalindromicNumberPattern
  Java/ParindromicNumPattern.java
Labels: hacktoberfest-accepted2023, hacktoberfest-accepted

#65 Added Maximum SubArray
  Java/MaxSubArray.java
Labels: hacktoberfest-accepted2023, hacktoberfest-accepted

#89 MinimumRecolorstogetKConsecutiveElements
  C++/MinimumRecolorstogetKconsecutivethings.cpp
Labels: hacktoberfest-accepted2023, hacktoberfest-accepted

#66 2D Word Search in cpp
  C++/2D-word-search.cpp
Labels: hacktoberfest-accepted2023, hacktoberfest-accepted
